### ISSUE TITLE
Add css units conversion

### ISSUE THREAD

**Issue by LeonFedotov** [ClickerMonkey/unitz#5]
It would require setting a reference for relative values calculations but I think it's worth it :+1:

**Comment by ClickerMonkey** [comment]
Because this is dependent on device (display resolution and whether the browser supports a unit), has a unit that interferes with an existing one (pt), and requires context like "relative to" and "width or height" I think the change just for CSS conversions would complicate the API quite a bit while only gaining functionality for CSS conversions.

I've written CSS conversions before - if you're interested in an implementation of this you can check it out here:

https://github.com/ClickerMonkey/anim8js/blob/master/lib/anim8js-dom-core.js#L252

Sorry, I don't think CSS units are a good match for this library!

**Comment by LeonFedotov** [comment]
@ClickerMonkey fair enough, thanks for the reply.
