### ISSUE TITLE
How would one return the next unit type down or up when not within the denominators?

### ISSUE THREAD

**Issue by jfrux** [ClickerMonkey/unitz#8]
For instance...

Ideally, in my app...
If a `cup` drops below `1/4 cup` into the `0.125 cup` it would read instead like... `2 tbsp`

Is this possible with this library?

**Comment by ClickerMonkey** [comment]
Yes, checkout the Unitz.best function!

Let me know if that suffices or not.

Thanks for using Unitz!

**Comment by jfrux** [comment]
Not exactly...

So I want it to say `1/4 cup` but I'm running the observed number through a multiplier.
If I chop the `0.25` it's spitting out `0.125 cups`.  Only then, would I want to use the step down which would be `2 fl oz` or whatever the next best thing is?

**Comment by jfrux** [comment]
I'm looking to calculate recipe ingredient amounts based on a base servings of 2.

At the base serving of 2, the amount was 1/4 cup (0.25 cup).

If I take it up to 3 servings, it moves up to next fraction correctly.

But if I move it down to 1 serving, the multiplier changes to 0.5 and the UnitzFraction drops below the denominator I guess, so it sets it to `0.125 cups` instead of the fraction.

I'm wondering if I should just use something like...
```
//psuedo code
if (!fraction.valid) { 
    parsed.best()
}
```

**Comment by ClickerMonkey** [comment]
I want this functionality as well - and any of the routes I've tried based on the current code aren't working currently (as desired). I think I'll work on this tonight:

```
Unitz.parse( '1/4 cup' ).scale( 0.5 );
```

If you don't like ounces you can also remove them so you get tbsp:
```
Unitz.classMap.Volume.groups.splice(2, 1);
```

This will keep that unit from showing up in `best()` results. I think I'm going to add a removeUnit as well to keep certain units out of the system.

**Comment by jfrux** [comment]
Noyyyceeee.

Thank you, yes I think it’s valuable!
Would add a ton of value for apps that use this sort of thing.

**Comment by jfrux** [comment]
Hmmm
![image](https://cloud.githubusercontent.com/assets/171077/24476603/ec90de32-14a1-11e7-9c9a-eec62336b481.png)

`1 0/2` cup?

**Comment by ClickerMonkey** [comment]
Can you provide the code to get that result so I can fix that as well?

**Comment by jfrux** [comment]
```javascript
Unitz.parse("0.875 cups").convert("cups",true,true).string //"1 0/2 cups"
```

**Comment by ClickerMonkey** [comment]
Okay - I have the fix for that, but it might not be what you're expecting (I can fix string variable). If you try to force a fraction of a unit you might end up with a "rounded" value. In this instance, it can't calculate a denominator available in cups `[2, 3, 4]` so it rounds to the nearest value it can in cups. In this instance, it's equally close to 3/4c and 1c and ends up picking 1c (when there's a value perfectly between the two it rounds up).

What are you trying to accomplish in that code example? (like - what functionality of your application you plan on using that for)

**Comment by jfrux** [comment]
It’s just for user’s changing the serving size of the recipe and it’s doing the math on the base serving of 2 for the recipe.

**Comment by ClickerMonkey** [comment]
I think it would also be useful to say something like this:

```javascript
Unitz.compound( '1.625 cups', ['c', 'tbsp'] ); 
// 1 1/2 cups, 2 tbsp
```

Basically use the left over of a fraction and convert it down to something smaller. Optionally saying "I only want units of c or tbsp since this is for a recipe and people don't measure in oz or pints"

**Comment by jfrux** [comment]
Completely agree.
How can I help?

If you give me some guidance of how you typically like things done and I can try to implement it?

**Comment by ClickerMonkey** [comment]
Release 0.5.0 was created and is accessible on NPM and Bower

Let me know how using `Unitz.compound` works out.

**Comment by ClickerMonkey** [comment]
Closing for now, let me know if any of the features won't suffice and I'll open it back up

**Comment by jfrux** [comment]
I like Unitz.compound, in theory...
However... if I don't feed it all the tiers that it requires, it does not appear to return the correct amount.

Maybe I'm missing the purpose of it.

So here goes my test.

```javascript
combinedAmounts = Unitz.combine("1/3 cup, 1.5 tbsp, 1.5 tbsp, 1.5 tbsp, 1.5 tbsp, 1.5 tbsp"); // 38.5 teaspoons

compoundTestOne = Unitz.compound(combinedAmounts,['c','tbsp','tsp']); // 1/2 c, 4 1/2 tbsp, 1 tsp

compoundTestTwo = Unitz.compound(combinedAmounts,['c']); // 1/2 c
```

`compoundTestOne` is correct because it adds up to `38.5 tsp`.
`compoundTestTwo` is not correct because it's only adding up to `24 tsp`. (1/2 cup)

I guess I just feel like it's kind of misleading maybe? Or maybe this is outside the scope of it's capabilities?  Maybe there should be a minimum of two units in the array?

Just thinking out loud, kind of brainstorming.

Am I doing something wrong or not understanding the purpose of it?

**Comment by ClickerMonkey** [comment]
My thought with those tiers would be for the application to define which units it wants to display to the user. So if the app only deals with cups then only pass c. If the app also wants to use tbsp and tsp it can. If you only pass c it will return the highest value and valid fraction that is equal to or less than the original value. If you only wanted a single value I think a call to convert would be more appropriate. Thoughts?

**Comment by jfrux** [comment]
Great, that's kind of how I thought it would work too...
However, the 1/2 cup wouldn't really be valid technically it would be closer to 3/4 cup.  The problem with THAT is, that since it's technically totaling more than 3/4 cup, we're not accurately expressing the measurement of ingredient.  I know, kind of a rock and a hard place.

There are many times where we aren't exactly able to hardcode the unit we want it in for the convert() function so I definitely think it's worth us spending time in case logic to get it working as someone would expect.

For instance, another place this might be useful but still isn't quite working as expected is time.
I think with a bit more massaging though, we could brain storm how we could make this work more precisely.

``` javascript
Unitz.compound("3000 seconds",["hr","min","s"]); // 1/2 hr, 20 min 
```
Currently I use Moment.js for this, but it's a bit of overkill just to compound the times into human readable format.

In this situation, I guess I'd expect this to return just 50 minutes.

I like the focus of this lib.
The reason I chose Unitz over other more complicated libs like Math.js, is because it's primary focus was not so much about complex math, as much as it was about it's ability to convert and output expressive, human-readable values to normal everyday things.

Please don't mistake all of the above as complaints, I commend you for your time and appreciate anything you throw at it.  I started to dig deeper into the code to see if I could help give back and contribute, I'd like to take the time to understand it more so I can find a good place to help out.

**Comment by ClickerMonkey** [comment]
Hey no problem, I want these things worked out as well - I created this library in preparation for an application I wanted to create, so your suggestions are good since you're actively using the ways I want to use it.

You're right there is a bug in compound, it finds the first correct fraction instead of the closest when looking at all possible fractions for a unit.

As far as your time example goes... 1 solution to that specific problem would be to remove 2 as a valid denominator from hour so that wouldn't show up. We don't really say 1/2hr IRL so it might not make sense. If you agree that a Unitz.setUnitDenominators should be added I can do that. 

Alternatively I could allow an object to be passed instead of an array of units where the object property is the unit and the value is the list of acceptable denominators. This is a little odd but would do the trick. 

If you can think of a better solution to these problems let me know. I definitely think Unitz needs some reworking done, there are many functions that assume all units, denominators, and assumes which unit you want in your text... ideally these would be configurable per method.

Thoughts?
